# Generated by Django 3.2 on 2021-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('movie_titel', models.CharField(blank=True, max_length=300, null=True)),
                ('movie_description', models.CharField(blank=True, max_length=500, null=True)),
                ('movie_genres', models.CharField(blank=True, max_length=200, null=True)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
