# Generated by Django 3.2 on 2021-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
